### ISSUE TITLE
Option to place center of object polygon  to other polygon center

### ISSUE THREAD

**Issue by nounaim** [egtwobits/mesh_mesh_align_plus#19] opened 2020-11-23 04:05 UTC
Now it like this
![](https://s8.gifyu.com/images/ezgif.com-resizeb147abdf190fc3c0.md.gif)
but I would like to like this
![](https://ibb.co/xz3wmJB][img]https://i.ibb.co/zPNC8GB/2222.jpg)
or somethink like "tack tool" in modo

**Comment by egtwobits** [comment] 2022-07-09 23:12
Might do this in a future release, dunno when though.

**Comment by egtwobits** [comment] 2022-07-09 23:19
I think this is a duplicate of Issue 20, closing this.

**Closed by egtwobits** 2022-07-09 23:19 UTC
